### ISSUE TITLE
MHC shouldn't remediate the reported terminal failures

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#3106]
**User Story**

As an Operator I would like MHC to avoid doing remediation on some specific `failureReason` and `failureMessage` that are terminal states, to avoid spamming the infrastructure and confuse the users.

**Detailed Description**

some Infrastructure have some terminal states where deleting and re-creating won't change the outcome (e.g. not enough quota, insufficient resources etc..). A solution to this would to allow t matching against `failureReason` and/or `failureMessage`(same mechanism as the taint/toleration) matching to select which failures we want to remediate against

**Anything else you would like to add:**

cc @vincepri @JoelSpeed @fabriziopandini 

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by fabriziopandini** [comment]
My hot take on this topic is the following:
- Remediation should be always explicitly requested by the administrator that configures MHC, so: 
  - MHC should not automatically remediate machines with failureMessage/Reason
  - There should be a knob in the MHC config allowing if to remediate machines with failureMessage/Reason & possibly a timeout
- failureMessage/Reason IMO is not the best API to rely on for remediation. So I'm not really keen of implementing some mechanism on top of it. TBH, I think we should deprecate those fields long term and use only conditions to express the object state.
- Instead, I would really like to get MHC being able to monitor also Machine Conditions (CAPI conditions) and not only node conditions.
- The ability to process CAPI conditions open many interesting possibilities for all the CAPI objects, not only for machines (e.g. configure a timeout for VPC provisioning on the AWS Cluster object)

**Comment by detiber** [comment]
This is actually quite interesting, since it would introduce a new "class" of errors.

Current "classes" of errors:
1) non-terminal error (does not set failure message/failure reason) and associated controller should attempt to retry on any subsequent reconciliation
2) terminal error (sets failure message/failure reason) and associated controller should not attempt to retry on any subsequent reconciliations

Potential new "classes" of errors:
1) non-terminal error, associated controller should attempt to retry on any subsequent reconciliations
2) local terminal error, associated controller should not attempt to retry on any subsequent reconciliations
3) global terminal error, associated controller should not attempt to retry on any subsequent reconciliations and any owning "aggregate" controller should not attempt additional operations that would create new resources with the same configuration

If we do find a way to encode these new "classes" of errors, I think it goes beyond just MHC and associated remediation, but also helps with the greater handling of scaling operations related to resources that are in a "global terminal error" state.

The tricky part will be encoding exactly what should be a global vs a local terminal error for various infrastructure providers. For example, using one of the given examples of quota, do we really want to consider that a global terminal error, since it is something that could either 1) resolve itself as pending terminations finish (using AWS as an example) or 2) be resolved through requesting additional quota.

I also agree with @fabriziopandini that failureMessage/failureReason might not be the best mechanism to use for differentiating types of terminal failures and conditions are probably a better path forward, as long as we have some way to do so without breaking the current contracts we have around failureMessage/failureReason.

**Comment by benmoss** [comment]
What about just using something like exponential backoffs instead of trying to classify which kinds of error are terminal and which are ephemeral? I think none of these are truly terminal, quotas can be raised, additional storage can be added, etc.

**Comment by detiber** [comment]
One example I can think of that would definitely be a "global terminal failure" would be something like specifying an invalid instance type or a root volume size that is less than the minimum required for a given imageID, either of those we could assume would never resolve.

+1 to adding some type of exponential backoff for "local terminal failure", though. The tricky part will be how to detect and track it.

**Comment by vincepri** [comment]
Going to set this to next for now until we understand the priority. Given the discussions above, unless there is a clear path, this probably can wait after the first implementation outlined in #3056 has been implemented and shipped.

/milestone Next

**Comment by yastij** [comment]
I'm fine with delaying this until #3056 is implemented

**Comment by JoelSpeed** [comment]
To add an additional example of a scenario:

If using a machine is backed by an AWS spot instance, except the maximum spot price is too low for the current price, it will fail to launch. Retrying this in a hot loop would be bad, but it isn't technically terminal because the price for the instance may eventually drop below the max price. So you would want to retry this periodically, which to me suggests we should look into some sort of back-off for MHC to cater for situations like this.

**Comment by vincepri** [comment]
Anyone interested in making this change?

I'll set the milestone to v1alpha4 for now, unless someone volunteers

/milestone v0.4.0

**Comment by vincepri** [comment]
@yastij @CecileRobertMichon This seems a behavioral breaking change that we should try making into v0.4.0 if possible

**Comment by slintes** [comment]
Hi folks, any thoughts on what Joel wrote above?
While we implemented (but didn't merge yet) the `failedNodeStartupTimeout` in Openshift first, we would like to know if the upstream community would accept the feature as described as well, in order to not diverge too much. Thanks :)

**Comment by CecileRobertMichon** [comment]
Just read the issue to catch up on context. @JoelSpeed's proposal seems useful for the specific use case he describes above, ie. "If using a machine is backed by an AWS spot instance, except the maximum spot price is too low for the current price, it will fail to launch", but it doesn't seem to solve the original use case described in the issue, ie. the idea of a "global terminal failure" where no amount of retrying is going to fix it. For example, the OS image provided doesn't exist, or the kubeadm config has an invalid value. In this case we wouldn't want to retry at all, even periodically with a backoff, since it won't magically fix itself unless the user intervenes. 

That being said, can you expand on why `nodeStartupTimeout` doesn't cover the same use case for machines that have a failure coming up? Wouldn't the `nodeStartupTimeout` also apply to Machines that "failed" to provision?

**Comment by sbueringer** [comment]
As discussed on 18 February in the backlog grooming, we think the right way forward is to deprecate failureMessage and failureReason and implement this based on conditions.

**Comment by fabriziopandini** [comment]
The Cluster API project currently lacks enough active contributors to adequately respond to all issues and PRs.

Considering that we never finalized the idea proposed by @JoelSpeed in 2021 (https://github.com/kubernetes-sigs/cluster-api/issues/3106#issuecomment-947466135) / follow up request from @CecileRobertMichon https://github.com/kubernetes-sigs/cluster-api/issues/3106#issuecomment-970528084, and that we would like to deprecate failureMessage and failureReason and implement this based on conditions as per https://github.com/kubernetes-sigs/cluster-api/issues/3106#issuecomment-1044989614

/close
