### ISSUE TITLE
"make generate" writes generated code to GOPATH/src and removes files from tree

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#4185]
**What steps did you take and what happened:**
Running `make generate` for me writes files to `$GOPATH/src` instead of the current working directory.

To reproduce:
```sh
mkdir /tmp/foo && cd /tmp/foo
git clone git@github.com:kubernetes-sigs/cluster-api.git
make generate
```

Logs from my run:
```console
0 ✓ (39.0ms) 19:35:55 invidian@dellxps15mateusz /tmp $ mkdir foo
0 ✓ (17.8ms) 19:35:58 invidian@dellxps15mateusz /tmp $ cd foo/
0 ✓ (20.9ms) 19:35:59 invidian@dellxps15mateusz /tmp/foo $ ls
0 ✓ (32.9ms) 19:35:59 invidian@dellxps15mateusz /tmp/foo $ ls -la
total 0
drwxr-xr-x   2 invidian invidian   40 Feb 11 19:35 .
drwxrwxrwt 316 root     root     9120 Feb 11 19:36 ..
0 ✓ (27.5ms) 19:36:00 invidian@dellxps15mateusz /tmp/foo $ git clone git@github.com:kubernetes-sigs/cluster-api.git
Cloning into 'cluster-api'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 107076 (delta 37), reused 18 (delta 12), pack-reused 107002
Receiving objects: 100% (107076/107076), 166.13 MiB | 8.10 MiB/s, done.
Resolving deltas: 100% (58749/58749), done.
0 ✓ (23.4s) 19:36:59 invidian@dellxps15mateusz /tmp/foo $ cd cluster-api/
0 ✓ (64.5ms) 19:37:00 invidian@dellxps15mateusz /tmp/foo/cluster-api (master)$ ls -l ~/go/src/
total 12
drwxr-xr-x 3 invidian invidian 4096 Jan 20 14:07 github.com
drwxr-xr-x 3 invidian invidian 4096 Jan 20 14:09 golang.org
drwxr-xr-x 3 invidian invidian 4096 Feb 11 18:11 sigs.k8s.io
0 ✓ (23.2ms) 19:37:04 invidian@dellxps15mateusz /tmp/foo/cluster-api (master)$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/invidian/.cache/go-build"
GOENV="/home/invidian/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/invidian/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/invidian/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/foo/cluster-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build585448041=/tmp/go-build -gno-record-gcc-switches"
0 ✓ (53.9ms) 19:37:07 invidian@dellxps15mateusz /tmp/foo/cluster-api (master)$ make generate
make generate-manifests
make[1]: Entering directory '/tmp/foo/cluster-api'
make generate-core-manifests
make[2]: Entering directory '/tmp/foo/cluster-api'
cd hack/tools; go build -tags=tools -o bin/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
/tmp/foo/cluster-api/hack/tools/bin/controller-gen \
        paths=./api/... \
        paths=./controllers/... \
        paths=./exp/api/... \
        paths=./exp/controllers/... \
        paths=./exp/addons/api/... \
        paths=./exp/addons/controllers/... \
        crd:crdVersions=v1 \
        rbac:roleName=manager-role \
        output:crd:dir=./config/crd/bases \
        output:webhook:dir=./config/webhook \
        webhook
/tmp/foo/cluster-api/hack/tools/bin/controller-gen \
        paths=./cmd/clusterctl/api/... \
        crd:crdVersions=v1 \
        output:crd:dir=./cmd/clusterctl/config/crd/bases
make[2]: Leaving directory '/tmp/foo/cluster-api'
make generate-kubeadm-bootstrap-manifests
make[2]: Entering directory '/tmp/foo/cluster-api'
/tmp/foo/cluster-api/hack/tools/bin/controller-gen \
        paths=./bootstrap/kubeadm/api/... \
        paths=./bootstrap/kubeadm/controllers/... \
        crd:crdVersions=v1 \
        rbac:roleName=manager-role \
        output:crd:dir=./bootstrap/kubeadm/config/crd/bases \
        output:rbac:dir=./bootstrap/kubeadm/config/rbac \
        output:webhook:dir=./bootstrap/kubeadm/config/webhook \
        webhook
make[2]: Leaving directory '/tmp/foo/cluster-api'
make generate-kubeadm-control-plane-manifests
make[2]: Entering directory '/tmp/foo/cluster-api'
/tmp/foo/cluster-api/hack/tools/bin/controller-gen \
        paths=./controlplane/kubeadm/api/... \
        paths=./controlplane/kubeadm/controllers/... \
        crd:crdVersions=v1 \
        rbac:roleName=manager-role \
        output:crd:dir=./controlplane/kubeadm/config/crd/bases \
        output:rbac:dir=./controlplane/kubeadm/config/rbac \
        output:webhook:dir=./controlplane/kubeadm/config/webhook \
        webhook
make[2]: Leaving directory '/tmp/foo/cluster-api'
make[1]: Leaving directory '/tmp/foo/cluster-api'
make generate-go
make[1]: Entering directory '/tmp/foo/cluster-api'
cd hack/tools; go build -tags=tools -o bin/go-bindata github.com/go-bindata/go-bindata/go-bindata
go generate ./...
make generate-go-core
make[2]: Entering directory '/tmp/foo/cluster-api'
cd hack/tools; go build -tags=tools -o bin/conversion-gen k8s.io/code-generator/cmd/conversion-gen
/tmp/foo/cluster-api/hack/tools/bin/controller-gen \
        object:headerFile=./hack/boilerplate/boilerplate.generatego.txt \
        paths=./api/... \
        paths=./exp/api/... \
        paths=./exp/addons/api/... \
        paths=./cmd/clusterctl/...
make clean-generated-conversions SRC_DIRS="./api/v1alpha3,./exp/api/v1alpha3,./exp/addons/api/v1alpha3"
make[3]: Entering directory '/tmp/foo/cluster-api'
(IFS=','; for i in ./api/v1alpha3,./exp/api/v1alpha3,./exp/addons/api/v1alpha3; do find $i -type f -name 'zz_generated.conversion*' -exec rm -f {} \;; done)
make[3]: Leaving directory '/tmp/foo/cluster-api'
/tmp/foo/cluster-api/hack/tools/bin/conversion-gen \
        --input-dirs=./api/v1alpha3 \
        --build-tag=ignore_autogenerated_core_v1alpha3 \
        --output-file-base=zz_generated.conversion \
        --go-header-file=./hack/boilerplate/boilerplate.generatego.txt
/tmp/foo/cluster-api/hack/tools/bin/conversion-gen \
        --input-dirs=./exp/api/v1alpha3 \
        --input-dirs=./exp/addons/api/v1alpha3 \
        --extra-peer-dirs=sigs.k8s.io/cluster-api/api/v1alpha3 \
        --output-file-base=zz_generated.conversion \
        --go-header-file=./hack/boilerplate/boilerplate.generatego.txt
make[2]: Leaving directory '/tmp/foo/cluster-api'
make generate-go-kubeadm-bootstrap
make[2]: Entering directory '/tmp/foo/cluster-api'
/tmp/foo/cluster-api/hack/tools/bin/controller-gen \
        object:headerFile=./hack/boilerplate/boilerplate.generatego.txt \
        paths=./bootstrap/kubeadm/api/... \
        paths=./bootstrap/kubeadm/types/...
make clean-generated-conversions SRC_DIRS="./bootstrap/kubeadm/api"
make[3]: Entering directory '/tmp/foo/cluster-api'
(IFS=','; for i in ./bootstrap/kubeadm/api; do find $i -type f -name 'zz_generated.conversion*' -exec rm -f {} \;; done)
make[3]: Leaving directory '/tmp/foo/cluster-api'
/tmp/foo/cluster-api/hack/tools/bin/conversion-gen \
        --input-dirs=./bootstrap/kubeadm/api/v1alpha3 \
        --build-tag=ignore_autogenerated_kubeadm_bootstrap_v1alpha3 \
        --extra-peer-dirs=sigs.k8s.io/cluster-api/api/v1alpha3 \
        --output-file-base=zz_generated.conversion \
        --go-header-file=./hack/boilerplate/boilerplate.generatego.txt
make[2]: Leaving directory '/tmp/foo/cluster-api'
make generate-go-kubeadm-control-plane
make[2]: Entering directory '/tmp/foo/cluster-api'
/tmp/foo/cluster-api/hack/tools/bin/controller-gen \
        object:headerFile=./hack/boilerplate/boilerplate.generatego.txt \
        paths=./controlplane/kubeadm/api/...
make clean-generated-conversions SRC_DIRS="./controlplane/kubeadm/api"
make[3]: Entering directory '/tmp/foo/cluster-api'
(IFS=','; for i in ./controlplane/kubeadm/api; do find $i -type f -name 'zz_generated.conversion*' -exec rm -f {} \;; done)
make[3]: Leaving directory '/tmp/foo/cluster-api'
/tmp/foo/cluster-api/hack/tools/bin/conversion-gen \
        --input-dirs=./controlplane/kubeadm/api/v1alpha3 \
        --build-tag=ignore_autogenerated_kubeadm_controlplane_v1alpha3 \
        --extra-peer-dirs=sigs.k8s.io/cluster-api/api/v1alpha3,sigs.k8s.io/cluster-api/bootstrap/kubeadm/api/v1alpha3 \
        --output-file-base=zz_generated.conversion \
        --go-header-file=./hack/boilerplate/boilerplate.generatego.txt
make[2]: Leaving directory '/tmp/foo/cluster-api'
make[1]: Leaving directory '/tmp/foo/cluster-api'
make generate-bindata
make[1]: Entering directory '/tmp/foo/cluster-api'
hack/ensure-kustomize.sh
fetching kustomize@3.9.1
kustomize
rm -rf cmd/clusterctl/config/manifest
/tmp/foo/cluster-api/hack/tools/bin/go-bindata -mode=420 -modtime=1 -pkg=cloudinit -o=bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go.tmp bootstrap/kubeadm/internal/cloudinit/kubeadm-bootstrap-script.sh
cat ./hack/boilerplate/boilerplate.generatego.txt bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go.tmp > bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go
rm bootstrap/kubeadm/internal/cloudinit/zz_generated.bindata.go.tmp
# Package manifest YAML into a single file.
mkdir -p cmd/clusterctl/config/manifest/
/tmp/foo/cluster-api/hack/tools/bin/kustomize build cmd/clusterctl/config/crd > cmd/clusterctl/config/manifest/clusterctl-api.yaml
# Generate go-bindata, add boilerplate, then cleanup.
/tmp/foo/cluster-api/hack/tools/bin/go-bindata -mode=420 -modtime=1 -pkg=config -o=cmd/clusterctl/config/zz_generated.bindata.go cmd/clusterctl/config/manifest/ cmd/clusterctl/config/assets
cat ./hack/boilerplate/boilerplate.generatego.txt cmd/clusterctl/config/zz_generated.bindata.go > cmd/clusterctl/config/manifest/manifests.go
cp cmd/clusterctl/config/manifest/manifests.go cmd/clusterctl/config/zz_generated.bindata.go
# Cleanup the manifest folder.
make clean-bindata
make[2]: Entering directory '/tmp/foo/cluster-api'
rm -rf cmd/clusterctl/config/manifest
make[2]: Leaving directory '/tmp/foo/cluster-api'
make[1]: Leaving directory '/tmp/foo/cluster-api'
make -C test/infrastructure/docker generate
make[1]: Entering directory '/tmp/foo/cluster-api/test/infrastructure/docker'
cd hack/tools; go build -tags=tools -o bin/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
make generate-manifests
make[2]: Entering directory '/tmp/foo/cluster-api/test/infrastructure/docker'
hack/tools/bin/controller-gen \
        paths=./api/... \
        paths=./exp/api/... \
        paths=./exp/controllers/... \
        paths=./controllers/... \
        crd:crdVersions=v1 \
        rbac:roleName=manager-role \
        output:crd:dir=./config/crd/bases \
        output:webhook:dir=./config/webhook \
        webhook
make[2]: Leaving directory '/tmp/foo/cluster-api/test/infrastructure/docker'
make generate-go
make[2]: Entering directory '/tmp/foo/cluster-api/test/infrastructure/docker'
cd hack/tools; go build -tags=tools -o bin/conversion-gen k8s.io/code-generator/cmd/conversion-gen
hack/tools/bin/controller-gen \
        object:headerFile=../../../hack/boilerplate/boilerplate.generatego.txt \
        paths=./api/... \
        paths=./exp/api/...
(IFS=','; for i in "./api/v1alpha3,./exp/api/v1alpha3"; do find $i -type f -name 'zz_generated.conversion*' -exec rm -f {} \;; done)
hack/tools/bin/conversion-gen \
        --input-dirs=./api/v1alpha3 \
        --input-dirs=./exp/api/v1alpha3 \
        --build-tag=ignore_autogenerated_capd_v1alpha3 \
        --extra-peer-dirs=sigs.k8s.io/cluster-api/api/v1alpha3 \
        --output-file-base=zz_generated.conversion \
        --go-header-file=../../../hack/boilerplate/boilerplate.generatego.txt
make[2]: Leaving directory '/tmp/foo/cluster-api/test/infrastructure/docker'
make[1]: Leaving directory '/tmp/foo/cluster-api/test/infrastructure/docker'
0 ✓ (2m33s) 19:39:42 invidian@dellxps15mateusz /tmp/foo/cluster-api (master)*$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    api/v1alpha3/zz_generated.conversion.go
        deleted:    bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
        deleted:    controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
        deleted:    exp/addons/api/v1alpha3/zz_generated.conversion.go
        deleted:    exp/api/v1alpha3/zz_generated.conversion.go
        deleted:    test/infrastructure/docker/api/v1alpha3/zz_generated.conversion.go
        deleted:    test/infrastructure/docker/exp/api/v1alpha3/zz_generated.conversion.go

no changes added to commit (use "git add" and/or "git commit -a")
```

**What did you expect to happen:**

Generate on freshly cloned repo behaves as expected.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Please let me know if I'm doing something wrong that I get this result.

**Environment:**

- Cluster-api version: 338375a908423a3843512ced6b9207ffcfcbf882
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fmuyassarov** [comment]
We had the same issue, and were asking the same on the [slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1610718111005800). We realized that, if clone the CAPI into the GOPATH, then you don't have this issue. As long as cloning happens outside of the GOPATH, then those auto-generated (zz) files get deleted.

**Comment by fmuyassarov** [comment]
But I'm not sure, if it is a strict requirement/prerequisite that CAPI has to be cloned within the GOPATH

**Comment by invidian** [comment]
Thanks @fmuyassarov. I think I actually experienced the same issue while working on Gardener. Perhaps this is a generic issue with the generator binaries then.

It would be nice to have a safety check in Makefile or have it documented, so new people don't run in that :)

**Comment by vincepri** [comment]
We should probably fix it to allow the repo to be cloned. Although IIRC this is a limitation in the generation code which is a dependency we have, not something we own.

**Comment by stmcginnis** [comment]
I just tested this locally and am no longer able to reproduce the issue.

macOS 10.15.7
go version: 1.15.7 (oops, time to upgrade)
Clone repo outside of `$GOPATH`.
Only noticed changes within `$GOPATH` were under `~/go/pkg`.
Observed files in repo being modified while the make target was running via `git status`.

I'm guessing this was fixed upstream and this particular issue can be closed now.

**Comment by fmuyassarov** [comment]
Hum, in my case the issue still persists. Just cloned the CAPI outside of the GOPATH and ran `make generate`, and still seeing

```
~/cluster-api$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    api/v1alpha3/zz_generated.conversion.go
	deleted:    bootstrap/kubeadm/api/v1alpha3/zz_generated.conversion.go
	deleted:    controlplane/kubeadm/api/v1alpha3/zz_generated.conversion.go
	deleted:    exp/addons/api/v1alpha3/zz_generated.conversion.go
	deleted:    exp/api/v1alpha3/zz_generated.conversion.go
	deleted:    test/infrastructure/docker/api/v1alpha3/zz_generated.conversion.go
	deleted:    test/infrastructure/docker/exp/api/v1alpha3/zz_generated.conversion.go

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by invidian** [comment]
Maybe we should create a reproducible case in Docker to be able to verify it.

**Comment by stmcginnis** [comment]
Looks like I may have been able to reproduce this. At first I thought it may be a difference between go1.15 and go1.16, but I've tried both versions with consistent results.

The difference I do see is running on macOS vs Linux. On the Mac, everything works fine and the files are updated in place as expected. On Linux, the files are deleted from the local repo and create under `$GOPATH/src`.

I can dig in to this tomorrow. I'll assign this to myself for now, but if anyone else wants to grab it and can get to it before I do, please feel free to do so.

/assign

**Comment by stmcginnis** [comment]
In case it helps anyone needing to reproduce this, I was able to do so on my Mac by doing the following:

```sh
docker run -it golang:1.16
git clone https://github.com/kubernetes-sigs/cluster-api
cd cluster-api
make generate
```

Or I'm sure you could mount the repo into the container and run from there.

**Comment by stmcginnis** [comment]
OK, I think I've got it sorted. Turns out the differences I was seeing in OS's was just a red herring.

The `conversion-gen` command we use has an optional arg of `--output-base`. From the help description of that arg:

```
Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set. (default "/go/src")
```

So where the files are generated can change depend on whether or not GOPATH is set and where it points to. If you do not have GOPATH set, then the files are generated where they are expected to be with the repo (default of `./`). But if GOPATH is actually set, then the files will be generated into `$GOPATH/src/`.

Easy enough fix - we should just be explicit about where to generate the files and set `--output-base=./` so behavior is not dependent on environment variables. Fix up shortly.

**Comment by invidian** [comment]
This still doesn't work as expected. Running in alpine container and cloning latest master (5f08b4ad3e87dcc4da6d1f923274d7e3ccd48c2a) gives this:
```console
        --input-dirs=./exp/api/v1alpha3 \
        --build-tag=ignore_autogenerated_capd_v1alpha3 \
        --extra-peer-dirs=sigs.k8s.io/cluster-api/api/v1alpha3 \
        --output-file-base=zz_generated.conversion --output-base=/usr/src/cluster-api/test/infrastructure/docker \
        --go-header-file=../../../hack/boilerplate/boilerplate.generatego.txt
make[2]: Leaving directory '/usr/src/cluster-api/test/infrastructure/docker'
make[1]: Leaving directory '/usr/src/cluster-api/test/infrastructure/docker'
/usr/src/cluster-api #
/usr/src/cluster-api # git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    bootstrap/kubeadm/types/v1beta1/zz_generated.conversion.go
        deleted:    bootstrap/kubeadm/types/v1beta2/zz_generated.conversion.go

no changes added to commit (use "git add" and/or "git commit -a")
/usr/src/cluster-api # ls /go/
bin  pkg  src
/usr/src/cluster-api # ls /go/src/
bootstrap
/usr/src/cluster-api # ls /go/src/bootstrap/
kubeadm
/usr/src/cluster-api # ls /go/src/bootstrap/kubeadm/
types
/usr/src/cluster-api # ls /go/src/bootstrap/kubeadm/types/
v1beta1  v1beta2
/usr/src/cluster-api # ls /go/src/bootstrap/kubeadm/types/v1beta
ls: /go/src/bootstrap/kubeadm/types/v1beta: No such file or directory
/usr/src/cluster-api # ls /go/src/bootstrap/kubeadm/types/v1beta1/
zz_generated.conversion.go
/usr/src/cluster-api #
```

Can we please re-open? I'll post full reproduction steps soon.

**Comment by invidian** [comment]
```sh
docker run -it --rm golang:alpine sh -c 'apk add -U git make bash curl gcc libc-dev && mkdir -p /usr/src && git clone https://github.com/kubernetes-sigs/cluster-api.git /usr/src/cluster-api && make -C /usr/src/cluster-api generate && git -C /usr/src/cluster-api diff --quiet'
```

It should return 0, but returns 1 right now.

**Comment by fabriziopandini** [comment]
@invidian, usually we avoid to reopen or comment on closed issue.
Please open a new one so we can start from a clean history
