### ISSUE TITLE
log kubeadm join into a file

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api#6448]
**User Story**

As an operator I would like to understand why sometimes `kubeadm join` fails to improve debugging issues with nodes not joining the cluster. 

**Detailed Description**

We recently had some troubles with windows nodes joining the cluster. In about 50% of the cases the join failed. This was often related to the time it took them to boot up and I suspect one reason was that the bootstrap token got invalidated by the time `kubeadm join` got executed. 
We're still investigating this issue and one way to gather more information is to have `kubeadm` log to a specified file. 

**Anything else you would like to add:**

[our fork contains a simple implementation](https://github.com/kubernetes-sigs/cluster-api/compare/main...helio:kubeadm-join-logs?expand=1) which works in linux and windows too. I'd be happy to provide this as a PR, though I'm not sure what kind of tests would need to be done to get this accepted. 

/kind feature

**Comment by fabriziopandini** [comment]
/milestone v1.2
As far as I'm aware of the output of kubeadm join gets logged into cloud init logs (this is the case for linux, not sure for windows). Does this works for you @mweibel?

Also we recently merged https://github.com/kubernetes-sigs/cluster-api/pull/6395 that can improve tolerance to slow joining machines

**Comment by mweibel** [comment]
#6395 helps indeed.

We added the log in our fork due to the fact that in windows, cloudbase-init only logs the details after it completed. That means when kubeadm join or another pre/post script is hanging for some reason, we don't see it at all, because the machine is shutdown before we see any logs. 
I haven't checked linux in detail (as in general there it just works), but I'd guess there it logs into a file continuously. 

I'm not sure if there's anything to influence logging on windows - might check that out as that would be the better solution.

**Comment by chrischdi** [comment]
I remember seeing this log issue to but I think this needs to get addressed at image-builder.

For linux it is because of this configuration: https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/05_logging.cfg#L67 .

` | python3 -c 'import sys,time;sys.stdout.write("".join(( " ".join((time.strftime("[%Y-%m-%d %H:%M:%S]", time.localtime()), line)) for line in sys.stdin )))'`

Seems to block until stdin closes.

**Comment by sbueringer** [comment]
Isn't this usually logged to cloud-init-output.log?

But could be that it's only logged there once the command finishes. Getting the logs live would be a big improvement

**Comment by mweibel** [comment]
> Isn't this usually logged to cloud-init-output.log?

Yes exactly. It's logged by cloudbase init (windows) but only once it's done. I believe (but since linux usually just works, haven't checked in detail) on linux this works. On windows not so much. 

> Also, we already made improvements to how kubeadm tokens are being managed, so if this was the use case this should not be a problem anymore

One issue we still face (using CAPZ + MachinePools) is that the updated bootstrrap tokens don't reach the VMSS (https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2683). That's CAPZ + externally managed autoscaler specific, however. 

This is not so important anymore, we found the issues related to join and addressed them. Not sure if you want to keep the issue open or close it until somebody finds it more important again. :)

**Comment by sbueringer** [comment]
> linux this is logged continuously

I think I remember that I also had to wait on Linux until kubeadm join / init (or rather all run commands in cloud-init) are done to get logs. It's a bit annoying.

IIRC (it's been a while) `journalctl -f` also receives does logs while they are produced.

**Comment by fabriziopandini** [comment]
@mweibel thanks for reporting back
I'm closing this for now
/close
